# Configuração do Sistema de Detecção de Objetos
# ===============================================

# Configurações da Câmera
camera:
  index: 0  # Índice da câmera (0 = padrão, 1 = externa)
  width: 640
  height: 480
  fps: 30
  buffer_size: 1  # Tamanho do buffer (menor = menos latência)

# Configurações do Modelo YOLO
model:
  path: "yolov8n.pt"  # Opções: yolov8n.pt, yolov8s.pt, yolov8m.pt, yolov8l.pt, yolov8x.pt
  confidence_threshold: 0.5  # Aumentado para reduzir detecções instáveis
  iou_threshold: 0.4  # Reduzido para melhor supressão
  device: "cpu"  # "cpu" ou "cuda"
  half_precision: false  # Usar half precision (GPU apenas)
  max_detections: 30  # Reduzido para melhor performance

# Configurações de Performance
performance:
  skip_frames: 0  # Processar todos os frames para eliminar piscar
  fps_calculation_window: 100  # Janela para média móvel do FPS
  enable_threading: true
  thread_pool_size: 2
  
# Configurações Anti-Flickering
stability:
  enable_tracking: true        # Ativar sistema anti-flickering
  detection_buffer_size: 3     # Manter detecções por N frames
  confidence_smoothing: 0.8    # Suavização de confiança (0-1)
  position_tolerance: 30       # Tolerância de posição em pixels
  min_stable_frames: 2         # Frames mínimos para mostrar detecção

# Configurações Visuais
display:
  window_name: "Object Detector - Enhanced"
  fullscreen: false            # Iniciar em tela cheia
  show_fps: true
  show_detection_count: true
  show_confidence: true
  box_thickness: 2
  font_scale: 0.5
  font_thickness: 1
  
  # Cores (BGR)
  colors:
    primary: [0, 255, 0]     # Verde
    text: [255, 255, 255]    # Branco
    background: [0, 0, 0]    # Preto
    fps: [0, 255, 255]       # Amarelo
    counter: [255, 255, 0]   # Ciano
    
  # Cores para classes de objetos
  class_colors:
    - [255, 0, 0]    # Azul
    - [0, 255, 0]    # Verde
    - [0, 0, 255]    # Vermelho
    - [255, 255, 0]  # Ciano
    - [255, 0, 255]  # Magenta
    - [0, 255, 255]  # Amarelo
    - [128, 0, 128]  # Roxo
    - [255, 165, 0]  # Laranja
    - [0, 128, 255]  # Azul claro
    - [128, 255, 0]  # Verde claro

# Configurações de Controle
controls:
  exit_keys: ['q', 'esc']
  pause_key: 'space'
  reset_key: 'r'
  performance_toggle_key: 'p'
  screenshot_key: 's'
  record_toggle_key: 'v'
  fullscreen_toggle_key: 'f'    # Alternar tela cheia

# Configurações de Gravação
recording:
  enabled: true
  output_dir: "recordings"
  codec: "XVID"  # Opções: "XVID", "MJPG", "MP4V"
  extension: ".avi"
  fps: 30

# Configurações de Log
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/detector.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
  console_output: true

# Configurações de Desenvolvimento
development:
  debug_mode: false
  profiling: false
  save_failed_frames: false
  performance_metrics: true 